Algoritmo "Exemplo 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Carlos
// Descrição   : Escrever um algoritmo que gera e escreve os números ímpares entre 100 e 200.
// Autor(a)    : Gisele Leite de Deus
// Data atual  : 13/04/2023

Var
// Seção de Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo