Algoritmo "Exemplo 4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Carlos
// Descrição   : Escreva uma programa que lê o sexo de uma pessoa. O sexo deverá ser com o tipo de dado caractere e o programa deverá aceitar apenas os valores "M" e "F".
// Autor(a)    : Gisele Leite de Deus
// Data atual  : 22/04/2023

Var

genero: caracter

Inicio

escreval("Digite seu genêro, usando apenas 'M' ou 'F'!)
leia(genero)


Fimalgoritmo
